### ISSUE TITLE
是单机版的吗？未来路线图种有集群化发展的考虑吗？

### ISSUE THREAD

**Issue by izyhme** [rulego/rulego#1]
是单机版的吗？未来路线图种有集群化发展的考虑吗？

**Comment by whki** [comment]
感谢您的反馈，暂时不考虑集群化的特性需求。
RuleGo 规则链处理数据流本身是无状态的，也不负责数据存储。
1.大数据场景，在上层的数据接收端对数据进行分流，然后接入RuleGo。
2.集群化有状态的数据计算场景，可以通过自定义组件去实现集群化。
