### ISSUE TITLE
请问有Hook（或者类似的机制）吗

### ISSUE THREAD

**Issue by fnoopv** [rulego/rulego#12]
我们准备做一个流程编排系统，需要记录各节点的流转状态，比如开始结束时间，耗时，输入，输出，日志等，目前可能需要一个Hook（或者类似的机制）在每个节点都执行上面说的相同的动作，我在现有的文档中没有找到类似的说明，请问现在有这样的机制吗？

**Comment by fnoopv** [comment]
符合但不是完全符合，比如时间信息，要想从这个方法里面拿到时间信息就需要节点主动传递，我们设计上是允许用户自定义节点的，这样的情况下就没办法保证这个情况。

**Comment by whki** [comment]
你说的是耗时吗？时间不需要主动传递。每个节点都会触发2次这个回调函数，分别是IN和OUT。从IN 记录start时间到OUT再记录end时间，这两个数之差就是这个节点的执行耗时。
