### ISSUE TITLE
节点依赖未生效

### ISSUE THREAD

**Issue by xiaoyan648** [rulego/rulego#13]
我现在想要实现服务编排的功能，并发获取不同服务的数据，然后在最后组合数据；

connections 如下：
```json
 "connections": [
      {
        "fromId": "s1",
        "toId": "s2",
        "type": "Success"
      },
      {
        "fromId": "s1",
        "toId": "s3",
        "type": "Success"
      },
      {
        "fromId": "s2",
        "toId": "s4",
        "type": "Success"
      },
      {
        "fromId": "s3",
        "toId": "s4",
        "type": "Success"
      }
    ],
```
按我的理解s4依赖s2、s3应该等到s2、s3都执行完毕才能执行，但现在的效果是s4执行了多次；

请问我应该如何实现这样的需求

**Comment by whki** [comment]
这样配置，是无法实现你的需求。节点会根据connections.type 找到它所有满足的子节点，然后并发执行。
你可以使用子规则链实现你的需求。把s2,s3这两个并发的节点放进子规则链，然后再接s4。类似这样：
https://rulego.cc/pages/6f46fc/#%E8%A7%84%E5%88%99%E9%93%BE%E6%94%AF%E6%8C%81%E7%9A%84%E8%BF%90%E8%A1%8C%E6%96%B9%E5%BC%8F
![image](https://github.com/rulego/rulego/assets/7507761/f217e5c7-6ee4-4161-ad7e-02b5069668c9)

子规则链文档：https://rulego.cc/pages/e27cec/
子规则链例子：https://github.com/rulego/rulego/blob/0739c78c70337a1a7ba82793574a613b02ebb9bc/testcases/rule_engine_test.go#L151

**Comment by xiaoyan648** [comment]
感谢你的回复，使用子链是可以满足需求的；
另外实现这个需求时，添加了一个grpc的组件，可以合并到项目中吗？

**Comment by whki** [comment]
> 感谢你的回复，使用子链是可以满足需求的； 另外实现这个需求时，添加了一个grpc的组件，可以合并到项目中吗？

谢谢你的贡献，我能否能访问你的仓库，我先看看。剥离业务，是一个通用的组件，可以合并的这个扩展组件仓库：https://github.com/rulego/rulego-components
方便的话，可以加一下我的微信或者QQ。

**Comment by xiaoyan648** [comment]
好的
