### ISSUE TITLE
Python runtime支持

### ISSUE THREAD

**Issue by ssrshz** [rulego/rulego#14]
没看到python runtime相关示例，目前还不支持吗

场景:
解决方案部，很多会写python，决策相关逻辑通过python实现，这样更利于推广

**Comment by whki** [comment]
目前 python runtime 还在TODO列表，预计在3月底会支持。

**Comment by whki** [comment]
也可以使用[ssh组件](https://rulego.cc/pages/fa62c1) ，通过shell命令方式执行Python脚本。

**Comment by whki** [comment]
因为Python需要安装CPython等依赖，暂时不考虑把Python内置到RuleGo中。可以通过自定义组件自行实现。
也可以使用[ssh组件](https://rulego.cc/pages/fa62c1) ，通过shell命令方式执行Python脚本。

另外最新加入了Lua运行时支持，在[扩展组件库](https://github.com/rulego/rulego-components) 可以使用Lua脚本对数据进行过滤、转换、增强等操作。也可以使用Lua脚本进行加解密、、网络、I/O、数据库等高级操作。
文档：
[luaFilter](https://rulego.cc/pages/5d61cc/)
[jsTransform](https://rulego.cc/pages/bf0eaf/)
