### ISSUE TITLE
是否支持空链，目前初始化空链后，onMsg 程序会直接 panic

### ISSUE THREAD

**Issue by H5Q4** [rulego/rulego#19]
{
  "ruleChain": {
    "id":"rule01"
  },
  "metadata": {
    "nodes": [
    ],
    "connections": [
    ]
  }
}
类似这样的空链，初始化没有问题，调用 onMsg 会 panic；既然允许这么初始化，onMsg 是否应该正常工作；或者提供空链的 check 方法。

**Comment by whki** [comment]
最新的main 分支的代码已经支持了
