### ISSUE TITLE
How does the restApiCall component add HTTP basic authentication credentials?

### ISSUE THREAD

**Issue by Loney1** [rulego/rulego#20]
![image](https://github.com/rulego/rulego/assets/49546802/3f3c072b-6c1a-4ee8-b8ea-42b3539529be)

**Comment by whki** [comment]
Place the authentication information into the `Authorization` header, configured like this.
```
 {
  "id": "s1",
  "type": "restApiCall",
  "name": "call api",
  "configuration": {
    "restEndpointUrlPattern": "http://xxx:9099/api/msg",
    "requestMethod": "POST",
    "headers": {
       “Authorization”:"Basic your_username:your_password"
      }
  }
}
```

**Comment by Loney1** [comment]
> Place the authentication information into the `Authorization` header, configured like this.
> 
> ```
>  {
>   "id": "s1",
>   "type": "restApiCall",
>   "name": "call api",
>   "configuration": {
>     "restEndpointUrlPattern": "http://xxx:9099/api/msg",
>     "requestMethod": "POST",
>     "headers": {
>        “Authorization”:"Basic your_username:your_password"
>       }
>   }
> }
> ```

Okay, thanks, I don't need to change the source code like it
<img width="834" alt="image" src="https://github.com/rulego/rulego/assets/49546802/6f49883e-4da9-40fc-b1c4-a06b2e369629">
