### ISSUE TITLE
如何保证流程中断后重启

### ISSUE THREAD

**Issue by exgalibas** [rulego/rulego#22]
请问rulego如何保证执行流程中断后重启还能断点续执行，是否有持久化的逻辑

**Comment by whki** [comment]
目前没有类似审批流的断点续执行的特性，后续可能会有。目前已经有了执行快照的信息，可以进一步扩展，满足你说需求场景。欢迎提供PR。
[RuleChainRunSnapshot](https://rulego.cc/pages/2bf5ef/)

**Comment by zxdstyle** [comment]
同样比较关注这个问题：
1. 怎么实现平滑重启，尽量不中断任务
2. 如果中断怎么继续接着执行

**Comment by whki** [comment]
> 同样比较关注这个问题：
> 
> 1. 怎么实现平滑重启，尽量不中断任务
> 2. 如果中断怎么继续接着执行

1. 已经实现了平滑热更新，不会中断任务。
2. 规则引擎是无状态的，需要用户执行保存执行过程的状态。后续框架会提供传入“快照数据”，从某个快照起点，继续执行，但快照数据需要用户自行保存。

**Comment by zxdstyle** [comment]
> > 同样比较关注这个问题：
> > 
> > 1. 怎么实现平滑重启，尽量不中断任务
> > 2. 如果中断怎么继续接着执行
> 
> 1. 已经实现了平滑热更新，不会中断任务。
> 2. 规则引擎是无状态的，需要用户执行保存执行过程的状态。
> 3. 后续框架会提供，保存“”执行快照“和传入“快照”，从某个快照起点，继续执行，但快照数据需要用户自行保存。

期待“快照”功能

**Comment by whki** [comment]
v0.22.0 提供了中断和恢复相关接口，参考这个[文档](https://rulego.cc/pages/4bb2d1/)
