### ISSUE TITLE
OnAllNodeCompleted 似乎不太符合预期，所有节点未完成就触发了，进而导致OnMsgAndWait没有阻塞进程

### ISSUE THREAD

**Issue by zxdstyle** [rulego/rulego#24]
<img width="702" alt="image" src="https://github.com/rulego/rulego/assets/38398954/0a5402e1-639a-4e38-8bf0-1cbffb72c8ca">

**Comment by whki** [comment]
OnEnd和OnDebug异步触发的，所以这里面打印顺序是不确定的。

**Comment by zxdstyle** [comment]
下面的Incoming message是log组件打印的，说明log组件没有执行完就调用OnAllNodeCompleted了

**Comment by zxdstyle** [comment]
<img width="516" alt="image" src="https://github.com/rulego/rulego/assets/38398954/c18c4b87-b655-4482-97f1-5da7eefecb50">

**Comment by whki** [comment]
应该是迭代器组件引起的，因为迭代器组件会执行多次，另外遍历完还会触发一个`Success`链导致提前判断结束。

**Comment by zxdstyle** [comment]
确实是迭代器组件的问题，去掉后运行正常

**Comment by whki** [comment]
v0.22.0将会提供新的[for组件](https://rulego.cc/pages/7db1de/) ，使用 [for组件](https://rulego.cc/pages/7db1de/) 代替。for组件会等待子链执行完再往下走。
