### ISSUE TITLE
What new features do you want RuleGo to add? Please leave a message here

### ISSUE THREAD

**Issue by whki** [rulego/rulego#3]
What new features do you want RuleGo to add? Please leave a message here.

**Comment by ogofly** [comment]
## 背景

我们在做的一个开源项目 https://github.com/ruffjs/tio，计划加入一个规则引擎 —— 还未确定是以库的方式内置到一个进程中或独立进程运行。  
作用主要是： 将设备的各种事件、MQTT 消息通过过滤、转换再输出到 MQTT 另外的 topic、数据库等。

## 问题
在过滤转换的过程中，需要消息本身之外的一些上下文信息，比如设备的基本信息、设备的 tag 信息等。  

1. 在使用 rulego 时，除了自定义一个 Node 来获取这些信息外，还有别的更合适的方式吗？ 
2. rulego 会长期支持以库的方式被集成吗？ —— 如果用自定义 Node 的方式来获取这些上下文信息，考虑到性能和延迟，一种可能的方式是希望与拥有上下文的程序在一个进程。

**Comment by whki** [comment]
### 问题一
规则链的消息（types.RuleMsg），会贯彻在整个规则链。 types.RuleMsg 主要包含几部分

- type: 事件/消息类型
- data: 消息payload
- metadata: 元数据，这个元数据的设计就是为了存放：设备的基本信息、设备的 tag 信息。建议您说的上下文信息存放在这里。 
例如：

``` go
metaData := types.NewMetadata()
metaData.PutValue("productType", "productType01")
metaData.PutValue("name", "test")
msg := types.NewMsg(0, "TEST_MSG_TYPE", types.JSON, metaData, "{\"aa\":\"aaaaaaaaaaaaaa\"}")
ruleEngine.OnMsg(msg)
```

如果是指针类型或者其他共享变量，也可以通过context.Context方式传递上下文。然后组件通过以下方式获取：

``` go
v := ctx.GetContext().Value(shareKey)
``` 

参考：[TestWithContext]('https://github.com/rulego/rulego/blob/main/testcases/rule_engine_test.go')      
参考：[component_test]('https://github.com/rulego/rulego/blob/main/testcases/component_test.go')    

### 问题二
rulego 会长期支持以库的方式被集成。      

- 通过metadata方式传递上下文,从目前的测试来看（包括在树莓派2上测试），没有太大性能的损耗，而且是上下文安全。
- 通过context.Context方式传递上下文，是函数调用方式，不会有性能和延迟问题。

**Comment by whki** [comment]
> ## 背景
> 我们在做的一个开源项目, 叫 [tio](https://github.com/ruffjs/tio)，类似一个轻量的 iothub，计划加入一个规则引擎。 这个规则引擎作用主要是： 将设备的各种事件、MQTT 消息通过过滤、转换再输出到 MQTT 另外的 topic、数据库等。
> 
> ## 问题
> 在过滤转换的过程中，需要消息本身之外的一些上下文信息，比如设备的基本信息、设备的 tag 信息等。
> 
> 1. 在使用 rulego 时，除了自定义一个 Node 来获取这些信息外，还有别的更合适的方式吗？
> 2. rulego 会长期支持以库的方式被集成吗？ —— 如果用自定义 Node 的方式来获取这些上下文信息，考虑到性能和延迟，一种可能的方式是希望与拥有上下文的程序在一个进程。

### 问题一
规则链的消息（types.RuleMsg），会贯彻在整个规则链。 types.RuleMsg 主要包含几部分

- type: 事件/消息类型
- data: 消息payload
- metadata: 元数据，这个元数据的设计就是为了存放：设备的基本信息、设备的 tag 信息。建议您说的上下文信息存放在这里。 
例如：

``` go
metaData := types.NewMetadata()
metaData.PutValue("productType", "productType01")
metaData.PutValue("name", "test")
msg := types.NewMsg(0, "TEST_MSG_TYPE", types.JSON, metaData, "{\"aa\":\"aaaaaaaaaaaaaa\"}")
ruleEngine.OnMsg(msg)
```

如果是指针类型或者其他共享变量，也可以通过context.Context方式传递上下文。然后组件通过以下方式获取：

``` go
v := ctx.GetContext().Value(shareKey)
``` 

参考：[TestWithContext]('https://github.com/rulego/rulego/blob/main/testcases/rule_engine_test.go')      
参考：[component_test]('https://github.com/rulego/rulego/blob/main/testcases/component_test.go')    

### 问题二
rulego 会长期支持以库的方式被集成。      

- 通过metadata方式传递上下文,从目前的测试来看（包括在树莓派2上测试），没有太大性能的损耗，而且是上下文安全。
- 通过context.Context方式传递上下文，是函数调用方式，不会有性能和延迟问题。

**Comment by ogofly** [comment]
感谢解答
