### ISSUE TITLE
dbClient查询列表时，遇到值为int64时，所有返回结果查询到值变成了相同的。

### ISSUE THREAD

**Issue by zhangminepng** [rulego/rulego#32]
**表结构为：**
CREATE TABLE `student` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '姓名',
  `age` int DEFAULT NULL COMMENT '年龄',
  PRIMARY KEY (`id`),
  KEY `student_name_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生表'
**表中数据有：**
id,name,age
1,张三,18
2,李四,26
3,张鹏,30
4,王五,23
5,赵六,56
6,李三,25
7,张三,27
**执行sql**
select * from student where name like '李%';
**得到结果：**
{"age":26,"id":2,"name":"李三"}
{"age":26,"id":2,"name":"李四"}
对应int的值变成了相同的。
**正确结果应为：**
{"age":25,"id":6,"name":"李三"}
{"age":26,"id":2,"name":"李四"}
经过源码跟踪，发现db_client_node.go文件query方法第233到237行的代码处理有问题，改成以下代码后得已解决
switch b1 := v.(type) {
```
case *interface{}:
switch b := (*b1).(type) {
case []byte:
	v = gus.ToStr(b)
default:
	v = b
}
default:
}
```
当然肯定也有其他解决办法。希望有遇到同类问题的可以借鉴。

**Comment by whki** [comment]
感谢你的反馈。已经修复，这段代码使用共享的指针变量，确实会出现你说的问题。但是我无法复现，可能和编译器或者数据库版本相关。麻烦帮忙验证一下。

**Comment by zhangminepng** [comment]
已经解决
