### ISSUE TITLE
是否考虑推出图形化界面的方式编辑规则的功能

### ISSUE THREAD

**Issue by bestwishCT** [rulego/rulego#34]

**Comment by whki** [comment]
已经有可视化规则链编辑器：[RuleGo-Editor](https://editor.rulego.cc/) 。
应用集成体验地址：[RuleGo-Sever](http://8.134.32.225:9090/ui/) 。
RuleGo-Editor目前是通过赞助少量费用方式，提供源码，可用于二次开发和应用集成，详细可以进群或者加我微信：rulegoteam 了解

**Comment by bestwishCT** [comment]
> 已经有可视化规则链编辑器：[RuleGo-Editor](https://editor.rulego.cc/) 。 应用集成体验地址：[RuleGo-Server](http://8.134.32.225:9090/ui/) 。 RuleGo-Editor目前是通过赞助少量费用方式，提供源码，可用于二次开发和应用集成，详细可以进群或者加我微信：rulegoteam 了解

感谢！
