### ISSUE TITLE
规则链执行异常会如何处理以及规则链外部存储示例？

### ISSUE THREAD

**Issue by kaleyroy** [rulego/rulego#55]
请教下哈

比如规则链当中某个节点写入数据库，因数据库短暂故障了无法写入，那势必会产生异常。
那这时候RuleGo如何处理？ 

- 会有记录本次执行的异常记录吗？ 
- 事后能否找出异常规则链，进行重试呢？

我看到文档有说Fallback策略，但是降级之后会短暂跳过当前故障的节点，对应的业务也就被跳过，对吧？

另外个问题是：

在examples/server 示例中，规则链信息保存在data/workflows文件夹下，
目前有实现将规则链信息以及规则链执行历史记录 保存到关系型数据的示例吗？

**Comment by whki** [comment]
1.你可以处理节点的“失败链”，如图:
![image](https://github.com/user-attachments/assets/1970bd10-93a1-4b08-b9ac-183cb0ab8e23)

你也可以当出现异常把当前状态保存下来，然后通过以下api进行中断恢复执行：
[https://rulego.cc/pages/4bb2d1/] (https://rulego.cc/pages/4bb2d1/)

2. 你可以根据规则链的 [DSL定义](https://github.com/rulego/rulego/blob/main/api/types/dsl.go)  和执行历史model，设计规则链的数据库表。欢迎进群交流，已经有人有这方面的经验

**Comment by kaleyroy** [comment]
> 1.你可以处理节点的“失败链”，如图: ![image](https://private-user-images.githubusercontent.com/7507761/398879114-1970bd10-93a1-4b08-b9ac-183cb0ab8e23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTM3NTksIm5iZiI6MTczNTI5MzQ1OSwicGF0aCI6Ii83NTA3NzYxLzM5ODg3OTExNC0xOTcwYmQxMC05M2ExLTRiMDgtYjlhYy0xODNjYjBhYjhlMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMDk1NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNhN2FlMTZhMDIxM2Y2OGZmZTYyZjk5MjJjYzQ5ZDc2YWI4ODUxZmI0MzlhYTQ4NzQ4ZjY1OGU4MjQ1MGQ1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qdtZMTOSKFjn0aKZ9b-oLuZCRaw_rVXWTjXoSOXYHHk)
> 
> 你也可以当出现异常把当前状态保存下来，然后通过以下api进行中断恢复执行： [https://rulego.cc/pages/4bb2d1/] (https://rulego.cc/pages/4bb2d1/)
> 
> 2. 你可以根据规则链的 [DSL定义](https://github.com/rulego/rulego/blob/main/api/types/dsl.go)  和执行历史model，设计规则链的数据库表。欢迎进群交流，已经有人有这方面的经验

明白了，感谢回复：）
